# EDA

## All Imports

In [1]:
import pandas as pd

## DATASET

In [2]:
df = pd.read_csv("../data/Pokedex_Ver_SV2.csv")
df.head()

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
0,1,1_0,Bulbasaur,Bulbasaur,1,0.7,6.9,Grass,Poison,Overgrow,...,65,65,45,318,0,0,0,1,0,0
1,2,2_0,Ivysaur,Ivysaur,1,1.0,13.0,Grass,Poison,Overgrow,...,80,80,60,405,0,0,0,1,1,0
2,3,3_0,Venusaur,Venusaur,1,2.0,100.0,Grass,Poison,Overgrow,...,100,100,80,525,0,0,0,2,1,0
3,3,3_1,Venusaur,Mega Venusaur,1,2.4,155.5,Grass,Poison,Thick Fat,...,122,120,80,625,0,0,0,2,1,0
4,4,4_0,Charmander,Charmander,1,0.6,8.5,Fire,NaN,Blaze,...,60,50,65,309,0,0,0,0,0,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1203 entries, 0 to 1202
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   No                   1203 non-null   int64
 1   Branch_Code          1203 non-null   object
 2   Original_Name        1203 non-null   object
 3   Name                 1203 non-null   object
 4   Generation           1203 non-null   int64
 5   Height               1203 non-null   float64
 6   Weight               1203 non-null   float64
 7   Type1                1203 non-null   object
 8   Type2                662 non-null    object
 9   Ability1             1203 non-null   object
 10  Ability2             588 non-null    object
 11  Ability_Hidden       932 non-null    object
 12  Color                1203 non-null   object
 13  Gender_Male          1203 non-null   float64
 14  Gender_Female        1203 non-null   float64
 15  Gender_Unknown       1203 non-null   int64
 16  Egg_Steps            1203 non-null   int64
 17  Egg_Group1           1203 non-null   object
 18  Egg_Group2           310 non-null    object
 19  Get_Rate             1203 non-null   int64
 20  Base_Experience      1203 non-null   int64
 21  Experience_Type      1203 non-null   int64
 22  Category             1203 non-null   object
 23  Mega_Evolution_Flag  48 non-null     object
 24  Region_Form          58 non-null     object
 25  HP                   1203 non-null   int64
 26  Attack               1203 non-null   int64
 27  Defense              1203 non-null   int64
 28  SP_Attack            1203 non-null   int64
 29  SP_Defense           1203 non-null   int64
 30  Speed                1203 non-null   int64
 31  Total                1203 non-null   int64
 32  E_HP                 1203 non-null   int64
 33  E_Attack             1203 non-null   int64
 34  E_Defense            1203 non-null   int64
 35  E_SP_Attack          1203 non-null   int64
 36  E_SP_Defense         1203 non-null   int64
 37  E_Speed              1203 non-null   int64
dtypes: float64(4), int64(20), object(14)
memory usage: 357.3+ KB

In [5]:
df[df["No"].duplicated()]

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
3,3,3_1,Venusaur,Mega Venusaur,1,2.4,155.5,Grass,Poison,Thick Fat,...,122,120,80,625,0,0,0,2,1,0
7,6,6_1,Charizard,Mega Charizard X,1,1.7,110.5,Fire,Dragon,Tough Claws,...,130,85,100,634,0,0,0,3,0,0
8,6,6_2,Charizard,Mega Charizard Y,1,1.7,100.5,Fire,Flying,Drought,...,159,115,100,634,0,0,0,3,0,0
12,9,9_1,Blastoise,Mega Blastoise,1,1.6,101.1,Water,NaN,Mega Launcher,...,135,115,78,630,0,0,0,0,3,0
19,15,15_1,Beedrill,Mega Beedrill,1,1.4,40.5,Bug,Poison,Adaptability,...,15,80,145,495,0,2,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152,964,964_1,Palafin,Palafin Hero Form,9,1.8,97.4,Water,NaN,Zero to Hero,...,106,87,100,650,2,0,0,0,0,0
1167,978,978_1,Tatsugiri,Tatsugiri Droopy Form,9,0.3,8.0,Dragon,Water,Commander,...,120,95,82,475,0,0,0,2,0,0
1168,978,978_2,Tatsugiri,Tatsugiri Stretchy Form,9,0.3,8.0,Dragon,Water,Commander,...,120,95,82,475,0,0,0,2,0,0
1173,982,982_1,Dudunsparce,Dudunsparce Three-Segment Form,9,4.5,47.4,Normal,NaN,Serene Grace,...,85,75,55,520,2,0,0,0,0,0
1191,999,999_1,Gimmighoul,Gimmighoul Roaming Form,9,0.1,0.1,Ghost,NaN,Run Away,...,75,45,80,300,0,0,0,1,0,0

In [6]:
df[df["Branch_Code"].duplicated()]

Empty DataFrame
Columns: [No, Branch_Code, Original_Name, Name, Generation, Height, Weight, Type1, Type2, Ability1, Ability2, Ability_Hidden, Color, Gender_Male, Gender_Female, Gender_Unknown, Egg_Steps, Egg_Group1, Egg_Group2, Get_Rate, Base_Experience, Experience_Type, Category, Mega_Evolution_Flag, Region_Form, HP, Attack, Defense, SP_Attack, SP_Defense, Speed, Total, E_HP, E_Attack, E_Defense, E_SP_Attack, E_SP_Defense, E_Speed]
Index: []

[0 rows x 38 columns]

In [7]:
df[df["Original_Name"].duplicated()]

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
3,3,3_1,Venusaur,Mega Venusaur,1,2.4,155.5,Grass,Poison,Thick Fat,...,122,120,80,625,0,0,0,2,1,0
7,6,6_1,Charizard,Mega Charizard X,1,1.7,110.5,Fire,Dragon,Tough Claws,...,130,85,100,634,0,0,0,3,0,0
8,6,6_2,Charizard,Mega Charizard Y,1,1.7,100.5,Fire,Flying,Drought,...,159,115,100,634,0,0,0,3,0,0
12,9,9_1,Blastoise,Mega Blastoise,1,1.6,101.1,Water,NaN,Mega Launcher,...,135,115,78,630,0,0,0,0,3,0
19,15,15_1,Beedrill,Mega Beedrill,1,1.4,40.5,Bug,Poison,Adaptability,...,15,80,145,495,0,2,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152,964,964_1,Palafin,Palafin Hero Form,9,1.8,97.4,Water,NaN,Zero to Hero,...,106,87,100,650,2,0,0,0,0,0
1167,978,978_1,Tatsugiri,Tatsugiri Droopy Form,9,0.3,8.0,Dragon,Water,Commander,...,120,95,82,475,0,0,0,2,0,0
1168,978,978_2,Tatsugiri,Tatsugiri Stretchy Form,9,0.3,8.0,Dragon,Water,Commander,...,120,95,82,475,0,0,0,2,0,0
1173,982,982_1,Dudunsparce,Dudunsparce Three-Segment Form,9,4.5,47.4,Normal,NaN,Serene Grace,...,85,75,55,520,2,0,0,0,0,0
1191,999,999_1,Gimmighoul,Gimmighoul Roaming Form,9,0.1,0.1,Ghost,NaN,Run Away,...,75,45,80,300,0,0,0,1,0,0

In [8]:
df[df["Name"].duplicated()]

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
1099,916,916_1,Oinkologne,Oinkologne,9,1.0,120.0,Normal,NaN,Aroma Veil,...,59,90,65,489,2,0,0,0,0,0

In [9]:
df[df["Generation"].isin([1,2,3,4,5,6,7,8,9])]

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
0,1,1_0,Bulbasaur,Bulbasaur,1,0.7,6.9,Grass,Poison,Overgrow,...,65,65,45,318,0,0,0,1,0,0
1,2,2_0,Ivysaur,Ivysaur,1,1.0,13.0,Grass,Poison,Overgrow,...,80,80,60,405,0,0,0,1,1,0
2,3,3_0,Venusaur,Venusaur,1,2.0,100.0,Grass,Poison,Overgrow,...,100,100,80,525,0,0,0,2,1,0
3,3,3_1,Venusaur,Mega Venusaur,1,2.4,155.5,Grass,Poison,Thick Fat,...,122,120,80,625,0,0,0,2,1,0
4,4,4_0,Charmander,Charmander,1,0.6,8.5,Fire,NaN,Blaze,...,60,50,65,309,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,1006,1006_0,Iron Valiant,Iron Valiant,9,1.4,35.0,Fairy,Fighting,Quark Drive,...,120,60,116,590,0,3,0,0,0,0
1199,1007,1007_0,Koraidon,Koraidon,9,2.5,303.0,Fighting,Dragon,Orichalcum Pulse,...,85,100,135,670,0,3,0,0,0,0
1200,1008,1008_0,Miraidon,Miraidon,9,3.5,240.0,Electric,Dragon,Hadron Engine,...,135,115,135,670,0,0,0,3,0,0
1201,1009,1009_0,Walking Wake,Walking Wake,9,3.5,280.0,Water,Dragon,Protosynthesis,...,125,83,109,590,0,0,0,3,0,0
1202,1010,1010_0,Iron Leaves,Iron Leaves,9,1.5,125.0,Grass,Psychic,Quark Drive,...,70,108,104,590,0,3,0,0,0,0

In [11]:
df[(df["HP"] < 10) | (df["HP"] > 250)]

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
303,242,242_0,Blissey,Blissey,2,1.5,46.8,Normal,NaN,Natural Cure,...,75,135,55,540,3,0,0,0,0,0
360,292,292_0,Shedinja,Shedinja,3,0.8,1.2,Bug,Ghost,Wonder Guard,...,30,30,40,236,2,0,0,0,0,0
1067,890,890_1,Eternatus,Eternamax Eternatus,8,100.0,0.0,Poison,Dragon,Pressure,...,125,250,130,1125,3,0,0,0,0,0

In [12]:
df[(df["Attack"] < 10) | (df["Attack"] > 250)]

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
150,113,113_0,Chansey,Chansey,1,1.1,34.6,Normal,NaN,Natural Cure,...,35,105,50,450,2,0,0,0,0,0
540,440,440_0,Happiny,Happiny,4,0.6,24.4,Normal,NaN,Natural Cure,...,15,65,30,220,1,0,0,0,0,0

In [13]:
df[(df["SP_Attack"] < 10) | (df["SP_Attack"] > 250)]

Empty DataFrame
Columns: [No, Branch_Code, Original_Name, Name, Generation, Height, Weight, Type1, Type2, Ability1, Ability2, Ability_Hidden, Color, Gender_Male, Gender_Female, Gender_Unknown, Egg_Steps, Egg_Group1, Egg_Group2, Get_Rate, Base_Experience, Experience_Type, Category, Mega_Evolution_Flag, Region_Form, HP, Attack, Defense, SP_Attack, SP_Defense, Speed, Total, E_HP, E_Attack, E_Defense, E_SP_Attack, E_SP_Defense, E_Speed]
Index: []

[0 rows x 38 columns]

In [14]:
df[(df["Defense"] < 10) | (df["Defense"] > 250)]

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
150,113,113_0,Chansey,Chansey,1,1.1,34.6,Normal,NaN,Natural Cure,...,35,105,50,450,2,0,0,0,0,0
540,440,440_0,Happiny,Happiny,4,0.6,24.4,Normal,NaN,Natural Cure,...,15,65,30,220,1,0,0,0,0,0

In [15]:
df[(df["SP_Defense"] < 10) | (df["SP_Defense"] > 250)]

Empty DataFrame
Columns: [No, Branch_Code, Original_Name, Name, Generation, Height, Weight, Type1, Type2, Ability1, Ability2, Ability_Hidden, Color, Gender_Male, Gender_Female, Gender_Unknown, Egg_Steps, Egg_Group1, Egg_Group2, Get_Rate, Base_Experience, Experience_Type, Category, Mega_Evolution_Flag, Region_Form, HP, Attack, Defense, SP_Attack, SP_Defense, Speed, Total, E_HP, E_Attack, E_Defense, E_SP_Attack, E_SP_Defense, E_Speed]
Index: []

[0 rows x 38 columns]

In [16]:
df[(df["Speed"] < 10) | (df["Speed"] > 250)]

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
270,213,213_0,Shuckle,Shuckle,2,0.6,20.5,Bug,Rock,Sturdy,...,10,230,5,505,0,0,1,0,1,0
547,446,446_0,Munchlax,Munchlax,4,0.6,105.0,Normal,NaN,Pickup,...,40,85,5,390,1,0,0,0,0,0
931,771,771_0,Pyukumuku,Pyukumuku,7,0.3,1.2,Water,NaN,Innards Out,...,30,130,5,410,0,0,0,0,2,0

In [17]:
df[df["Total"] != df["HP"] + df["Attack"] + df["SP_Attack"] + df["Defense"] + df["SP_Defense"] + df["Speed"]]

Empty DataFrame
Columns: [No, Branch_Code, Original_Name, Name, Generation, Height, Weight, Type1, Type2, Ability1, Ability2, Ability_Hidden, Color, Gender_Male, Gender_Female, Gender_Unknown, Egg_Steps, Egg_Group1, Egg_Group2, Get_Rate, Base_Experience, Experience_Type, Category, Mega_Evolution_Flag, Region_Form, HP, Attack, Defense, SP_Attack, SP_Defense, Speed, Total, E_HP, E_Attack, E_Defense, E_SP_Attack, E_SP_Defense, E_Speed]
Index: []

[0 rows x 38 columns]

In [18]:
df["Category"].unique()

array(['Ordinary', 'Semi-Legendary', 'Legendary', 'Mythical'],
      dtype=object)

In [19]:
df["Region_Form"].unique()

array([nan, 'Alolan', 'Galarian', 'Hisuian', 'Paldean'], dtype=object)

In [20]:
df["Type1"].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Dark', 'Poison',
       'Electric', 'Ground', 'Ice', 'Fairy', 'Steel', 'Fighting',
       'Psychic', 'Rock', 'Ghost', 'Dragon', 'Flying'], dtype=object)

In [21]:
df["Type2"].unique()

array(['Poison', nan, 'Flying', 'Dragon', 'Normal', 'Psychic', 'Steel',
       'Ground', 'Fairy', 'Grass', 'Rock', 'Fighting', 'Electric', 'Ice',
       'Dark', 'Ghost', 'Fire', 'Water', 'Bug'], dtype=object)